### ISSUE TITLE
Update Readme to indicate relationship with CAJ

### ISSUE THREAD

**Issue by slominskir** [channelaccess/ca#22]
Should I be using Channel Access Java (CAJ) or this library.   Is this library production ready?  Is anyone using it?  By the way the name "ca" is so generic it is tricky to search for.  Maybe you should have given this library a clever name like CAJ2.

**Comment by simongregorebner** [comment]
There is absolute no relationship to CAJ/JCA (except that we are using the channel access server part of CAJ/JCA  for unit testing for this library) so we don't mention it in the Readme. The concept of this library is based on a different approach than CAJ so CAJ2 would completely miss the point. Beside that, the generic name is by intention.

We at the Paul Scherrer Institute are using this library for production purposes (there would have been no point in developing and sharing it otherwise).

If we can help you with more details, please let us know.
