### ISSUE TITLE
Readme unclear about supported listeners

### ISSUE THREAD

**Issue by jlmuir** [channelaccess/ca#53]
The file `Readme.md` contains the following item in the Features section:

> Support of all listeners ChannelAccess supports: ConnectionListener, AccessRightListener, Value Listener (Monitor)

It's unclear to me what that means.  Is it saying that it supports similar listening to what can be done in a JCA implementation?

JCA contains the interfaces `ConnectionListener`, `AccessRightsListener`, and `MonitorListener` (among others).  If that's what this is referring to, then perhaps the item should read as follows:

Supports listening to all Channel Access events that can be listened to with a JCA implementation (e.g., similar to JCA's `ConnectionListener`, `AccessRightListener`, `MonitorListener`, etc.)

**Comment by simondelabici** [comment]
@jlmuir 

Thanks for the feedback and, yes, you are right the Readme file seems rather ambiguous. It wasn't clear to me, either, whether the comment referred to JCA or to the features supported by the channel access protocol itself.

I will modify the text to say what is explicitly supported directly, rather than what is supported by reference to some other (currently unspecified) implementations. 

Thus:-
```
* Supports channel monitoring including mask capability to select events-of-interest (eg value, log, alarm 
and/or property changes).
* Supports the following listeners: ConnectionListener, AccessRightsListener.
```
